### ISSUE TITLE
Struggle understanding the architecture

### ISSUE THREAD

**Issue by jess-sys** [danielkucera/vpnmcast#4]
Hey, thanks for your work!

I'm trying to setup vpnmcast, but I don't really understand on which side of the VPN it should be installed.

From my understanding, it should be installed on the machine connected to the internet with the public IP. Is that right ?

Also, I'm already running igmp-proxy. Can they both listen at the same time ?

Thanks!

**Comment by danielkucera** [comment]
Hi Jessy,

the expected use case is that you have a OpenVPN server with access to multicasts over local interface and you want to forward these to VPN clients.

It's supposed to run on the server and should also work if you are running igmpproxy simultaneously.

**Comment by jess-sys** [comment]
Hey, thank you for your fast answer.

Here's what I'd like to achieve:
![image](https://user-images.githubusercontent.com/20131496/113447026-5957d400-93f9-11eb-9c06-d105ae89effd.png)

From my understanding, once the OpenVPN session is established, I just have to run vpnmcast on the router, add the tap interface to igmpproxy and it'll work ?

**Comment by danielkucera** [comment]
If you have only one openvpn client, you dont need vpnmcast (it's only for directing mcasts to specific clients, otherwise it's handled as broadcast by default), just another igmpproxy on debian box

**Comment by jess-sys** [comment]
Awesome! Thanks again.
